apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.secret.name }} #fastapi-secret
  labels:
    app: {{ .Values.app.labels.app }} #fastapi
data: # echo -n "postgres:..." | base64
  DB_URL: cG9zdGdyZXNxbDovL2hlbGxvX2Zhc3RhcGk6aGVsbG9fZmFzdGFwaUBwb3N0Z3Jlcy1zZXJ2aWNlL2hlbGxvX2Zhc3RhcGlfZGV2