apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.service.name }} #fastapi-service
  labels:
    app: {{ .Values.app.labels.app }} #fastapi-postgres-demo
spec:
  type: {{ .Values.app.service.type }} #NodePort # For INGRESS ClusterIP can be used as well instead of NodePort
  selector:
    app: {{ .Values.app.deploy.labels.app }} #fastapi
  ports:
    - name: http
      port: {{ .Values.app.service.ports.port }} #8000
      targetPort: {{ .Values.app.service.ports.targetPort }} #8000
      protocol: TCP