apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi-postgres-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      initContainers:
        - name: init-postgres-service
          image: postgres:13.1-alpine
          command: ['sh', '-c',
            'until pg_isready -h postgres-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local -p 5432;
            do echo waiting for database; sleep 2; done;']

      containers:
        - name: fastpi-container
          image: haerschke/fastapi_postgres:2.0
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: fastapi-secret
                key: DB_URL
          ports:
            - containerPort: 8000
