apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
  labels:
    app: fastapi-postgres-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
        - name: fastpi-container
          image: haerschke/fastapi_postgres:2.0
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: fastapi-secret
                key: DB_URL
          ports:
            - containerPort: 8000
