apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
  labels:
    app: fastapi-postgres-demo
spec:
  type: NodePort # For INGRESS ClusterIP can be used as well instead of NodePort
  selector:
    app: fastapi
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP